### ISSUE TITLE
Necromancer is unable to summon undead pawns

### ISSUE THREAD

**Issue by vonMort** [TorannD/RWoM#41]
Hey my man!
First - thanks for the quick 1.4 update. I really love to play with magic.

I currently started a run with a solo necromancer and tried multiple times to rise undead pawns. With animals that worked just fine at first try. But with colonists, raiders or anything humanlike the always get back alive as "normal" pawns and are just directly enslaved.

Would be nice if you could look into that!

https://user-images.githubusercontent.com/97391434/198259481-263ec4fd-43a5-456c-84a7-844ab7efc536.mp4

**Comment by TorannD** [comment]
Resolved, thanks for the report.
