### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by CIVITAS-John** [TorannD/RWoM#7]
In `CompAbilityUserMagic.cs`, there is a bug that would cause a significant performance drop:

```
Enchantment.CompProperties_Enchant newEnchantComp = new Enchantment.CompProperties_Enchant();
this.Pawn.def.comps.Add(newEnchantComp);
```

Please consider fixing it as it would significantly degrade the performance especially when loading/saving multiple times.

Thanks!

**Comment by TorannD** [comment]
I removed the try block; this was probably a remnant of initial implementation where pre-generated pawns didn't have the comp.
