### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by feeddanoob** [TorannD/RWoM#76]
Not sure which update to RWoM caused the NRE, but when using it with a near min load order I get the errors in the [HugsLib](https://gist.github.com/feeddanoob/fe3f8978cdce946033c91c50bf9beb8d). This error occurred when randomizing a pawn multiple times during pawn creation. I thought it was a compatibility issue with Vanilla Expanded Framework (and the mods that require it) but it turned out to be a RWoM issue.

**Comment by TorannD** [comment]
Resolved
