### ISSUE TITLE
NullReferenceException in PreApplyDamage_Patch method causes pawns to take no damage whatsoever

### ISSUE THREAD

**Issue by gerusz** [TorannD/RWoM#78]
If it was only me, I would probably try to resolve the conflict in my modlist. But apparently other players are experiencing this problem. Log exerpt:

Exception ticking Arrow_Recurve491510: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 3DC86C69]
 at TorannMagic.TorannMagicMod+PreApplyDamage_Patch.Prefix (Verse.Pawn_HealthTracker __instance, Verse.Pawn ___pawn, Verse.DamageInfo& dinfo, System.Boolean& absorbed) [0x0125b] in <af7b06a4a2a241d49f87748b7f8fc155>:0 
     - TRANSPILER PerformanceOptimizer.Main: IEnumerable`1 PerformanceOptimizer.Optimization_FasterGetCompReplacement:Transpiler(IEnumerable`1 instructions, MethodBase method)
 at Verse.Pawn_HealthTracker.PreApplyDamage (Verse.DamageInfo dinfo, System.Boolean& absorbed) [0x00081] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - TRANSPILER Harmony_PrisonLabor: IEnumerable`1 PrisonLabor.HarmonyPatches.Triggers+Trigger_PreApplyDamage:Transpiler(IEnumerable`1 instr)
     - PREFIX jecstools.jecrell.main: Boolean JecsTools.HarmonyPatches:PreApplyDamage_PrePatch(Pawn ___pawn, DamageInfo& dinfo, Boolean& absorbed)
     - PREFIX jecstools.chjees.shields: Boolean PawnShields.HarmonyPatches:Patch_Pawn_HealthTracker_PreApplyDamage(Pawn ___pawn, DamageInfo& dinfo, Boolean& absorbed)
     - PREFIX rimworld.jecrell.jedi: Boolean ProjectJedi.HarmonyPatches:PreApplyDamage_PreFix(Pawn_HealthTracker __instance, DamageInfo dinfo, Boolean& absorbed)
     - PREFIX Torann.ARimworldOfMagic: Boolean TorannMagic.TorannMagicMod+PreApplyDamage_Patch:Prefix(Pawn_HealthTracker __instance, Pawn ___pawn, DamageInfo& dinfo, Boolean& absorbed)
     - POSTFIX com.cyanobot.cyanobotsgenes: Void CyanobotsGenes.DiedOrDownedThoughts_AppendThoughts_ForHumanlike_Patch+PreApplyDamage_Patch:Postfix(Pawn ___pawn, DamageInfo dinfo, Boolean absorbed)
     - POSTFIX doug.conn: Void CONN.Pawn_HealthTracker_PreApplyDamage:Pawn_HealthTracker_PreApplyDamagePostfix(Pawn_HealthTracker __instance, DamageInfo dinfo, Pawn ___pawn)
 at Verse.Pawn.PreApplyDamage (Verse.DamageInfo& dinfo, System.Boolean& absorbed) [0x000a7] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - PREFIX jecstools.jecrell.main: Void JecsTools.HarmonyPatches:Pawn_PreApplyDamage_Prefix(DamageInfo& dinfo, Single& __state)
     - PREFIX Torann.ARimworldOfMagic: Boolean TorannMagic.TorannMagicMod+Pawn_PreApplyDamage:Prefix(Pawn __instance, DamageInfo& dinfo, Boolean& absorbed)
     - POSTFIX VREHussars.Mod: Void VREHussars.Pawn_PreApplyDamage_Patch:Postfix(Pawn __instance, DamageInfo& dinfo)
     - POSTFIX VanillaExpanded.VFEA: Void VFEAncients.PowerWorker_Blunt:SurfaceOnly(Pawn __instance, DamageInfo& dinfo)
     - POSTFIX jecstools.jecrell.main: Void JecsTools.HarmonyPatches:Pawn_PreApplyDamage_Postfix(Pawn __instance, DamageInfo& dinfo, Boolean& absorbed, Single __state)
 at Verse.Thing.TakeDamage (Verse.DamageInfo dinfo) [0x0016b] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - PREFIX Neronix17.TabulaRasa.RimWorld: Boolean TabulaRasa.Patch_Thing_TakeDamage:Prefix(DamageInfo dinfo, Thing& __instance, DamageResult& __result)
     - PREFIX OskarPotocki.VFECore: Void AnimalBehaviours.Patch_TakeDamage:Prefix(Thing __instance, DamageInfo dinfo)
     - PREFIX ReBuildDoorsAndCornersMod: Void ReBuildDoorsAndCorners.Thing_TakeDamage_Patch:Prefix(Thing __instance, DamageInfo& dinfo)
     - PREFIX VanillaExpanded.VFEA: Void VFEAncients.PowerWorker_Damages:ChangeDamage(DamageInfo& dinfo, Thing __instance)
     - PREFIX jecstools.jecrell.comps.deflector: Boolean CompDeflector.HarmonyCompDeflector:TakeDamage_PreFix(Thing __instance, DamageInfo& dinfo)
     - PREFIX rimworld.jecrell.jedi: Void ProjectJedi.HarmonyPatches:TakeDamage_PreFix(DamageInfo& dinfo)
     - PREFIX OskarPotocki.VanillaFactionsExpandedMechanoids: Void VFEMech.Thing_TakeDamage_Patch:Prefix(Thing __instance, DamageInfo& dinfo)
     - POSTFIX OskarPotocki.VFECore: Void VFECore.Patch_Thing_TakeDamage:Postfix(Thing __instance, DamageInfo dinfo)
     - POSTFIX com.CaesarV6.DamageMotes.Patch: Void DamageMotes.DamageMotes_Patch:Postfix(DamageInfo dinfo, Thing __instance, DamageResult __result)
     - POSTFIX OskarPotocki.VanillaTraitsExpanded: Void VanillaTraitsExpanded.TakeDamage_Patch:Postfix()
 at RimWorld.Bullet.Impact (Verse.Thing hitThing, System.Boolean blockedByShield) [0x0010d] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - PREFIX SmashPhil.VehicleFramework: Boolean Vehicles.Combat:BulletImpact(Thing hitThing, Projectile __instance, Thing ___launcher)
 at Verse.Projectile.ImpactSomething () [0x002ef] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - TRANSPILER OskarPotocki.VFECore: IEnumerable`1 VFECore.Projectile_SetTrueOrigin:Transpiler(IEnumerable`1 codeInstructions)
     - TRANSPILER SmashPhil.VehicleFramework: IEnumerable`1 Vehicles.Combat:VehicleProjectileChanceToHit(IEnumerable`1 instructions)
     - PREFIX VanillaExpanded.VFEA: Boolean VFEAncients.HarmonyPatches.PointDefensePatches:PreImpactSomething(Projectile __instance)
     - POSTFIX OskarPotocki.VFECore: Void VFEMech.TeslaProjectile+ProjectilePatches:Postfix()
 at Verse.Projectile.Tick () [0x0011f] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0 
     - POSTFIX OskarPotocki.VFECore: Void VFECore.Projectile_Tick_Patch:Postfix(Projectile __instance)
 at Verse.TickList.Tick () [0x0015c] in <f0ac5eb9b52e4cc396c70fc9a4ee15e5>:0  

Seems like you forgot a null-check somewhere in that method. The game used to work before the latest update of this mod.

**Comment by TorannD** [comment]
Resolved
